require_relative "shifts"
require "date"
require "pastel"

class CLI
  PASTEL = Pastel.new
  # available commands
  # shifts hours me thisweek/nextweek
  # shifts hours name thisweek/nextweek
  # shifts willsee name name thisweek/nextweek
  def self.run(argv)
    command = argv.shift ## ARGV now contains remaining data 
    
    
    
    case command.downcase
    when "hours", "hrs", "h"
      hours(argv)
    when "willsee", "wsee", "ws"
      willsee(argv)
    when "whosin", "who", "wh"
      whosin(argv)
    when "glifetime", "glife"
      glifetime(argv)
    when "lifetime", "life"
      lifetime(argv)
    when "help"
      help
    when "rota", "r"
      rota(argv)
    else 
      abort "Unknown command: #{command}"
    end
    
    
    
  end

  def self.define_period(period)
    period = period.strip.downcase
    case period
    when "thisweek", "tweek", "tw"
      Dates.this_week
    when "today", "tod"
      Dates.today
    when "tomorrow", "tom"
      Dates.tomorrow
    when "yesterday", "yes"
      Dates.yesterday
    when "friday", "fri"
      Dates.friday
    when "saturday", "sat"
      Dates.saturday
    when "sunday", "sun"
      Dates.sunday
    when "monday", "mon"
      Dates.monday
    when "tuesday", "tue"
      Dates.tuesday
    when "wednesday", "wed"
      Dates.wednesday
    when "thursday", "thu"
      Dates.thursday

    # next week
    when "nextweek", "nweek", "nw"
      Dates.next_week
    when "nfriday", "nfri"
      Dates.nfriday
    when "nsaturday", "nsat"
      Dates.nsaturday
    when "nsunday", "nsun"
      Dates.nsunday
    when "nmonday", "nmon"
      Dates.nmonday
    when "ntuesday", "ntue"
      Dates.ntuesday
    when "nwednesday", "nwed"
      Dates.nwednesday
    when "nthursday", "nthu"
      Dates.nthursday

    # last week
     when "lastweek", "lweek", "lw"
      Dates.last_week
     when "lthursday", "lthu"
      Dates.lthursday
     when "lwednesday", "lwed"
      Dates.lwednesday
     when "ltuesyday", "ltue"
      Dates.ltuesday
     when "lmonday", "lmon"
      Dates.lmonday
     when "lsunday", "lsun"
      Dates.lsunday
     when "lsaturday", "lsat"
      Dates.lsaturday
      when "lfriday", "lfri"
      Dates.lfriday
      
    else
      Dates.parse_arg(period)
    end
  end

  def self.hours(argv)
    date = get_date(argv.pop)
    employees = get_employees(date)
    if argv[0].downcase == "me"
      shifts = Roster.shifts_for(employees, ENV["MY_NAME"])
    else
      shifts = Roster.shifts_for(employees, argv[0].downcase)
    end
    shift_data = Calculator.calc_shift_data(shifts, start_key: "startTime", end_key: "endTime")
    ShiftFormatter.format_shift_data(shift_data)
  end

  def self.willsee(argv)
    date = get_date(argv.pop)
    employees = get_employees(date)
    abort "Invalid format, format must be shifts willsee NAME NAME thisweek/nextweek" unless argv.size == 2
    p1 = argv[0].downcase
    p2 = argv[1].downcase
    p1_data = Calculator.calc_shift_data(Roster.shifts_for(employees, p1), start_key: "startTime", end_key: "endTime")
    p2_data = Calculator.calc_shift_data(Roster.shifts_for(employees, p2), start_key: "startTime", end_key: "endTime")
    result = Roster.find_shifts_in_common(employees, p1_data, p2_data)
    ShiftFormatter.format_shifts_in_common(result)
  end

  def self.whosin(argv)
    date = get_date(argv.last)
    employees = get_employees(date)
    shifts = Roster.shifts_by_date(employees, date)
    shifts.each do |shift|
      ShiftFormatter.format_shift(shift)
    end
  end

  def self.glifetime(argv)
    date = get_date(argv.pop)
    name = argv.pop
    client = Client.new
    employees = client.get_employees(date)
    data = Analytics.calc_lifetime_data(employees, name, date, client)
    pp data
  end

  def self.lifetime(argv)
    name = argv.last
    data = Analytics.retrieve_lifetime_data(name)
    pp data
  end

  def self.rota(argv)
    date = get_date(argv.pop)
    client = Client.new
    employees = client.get_employees(date)
    data = Roster.full_roster_info(employees, date)
    Roster.generate_roster_table(data, date)
  end

  def self.help
    puts PASTEL.green.bold ("HELP")
    line_break("+")
    puts PASTEL.blue.bold "Available commands"
    line_break("+")
    puts PASTEL.yellow.bold "hours (alias hrs, h) - format: shifts hours NAME DATE"
    line_break("-")
    puts PASTEL.bright_red.bold "willsee (alias wsee, ws) - format: shifts willsee NAME NAME DATE"
    line_break("-")
    puts PASTEL.bright_blue.bold "whosin (alias who, wh) - format: shifts whosin DATE (specific day)"
    line_break("-")
    puts PASTEL.bright_magenta.bold "glifetime (alias glife) - format: shifts glifetime NAME DATE (lastweek if employee still on roster, date of leaving week if not)"
    line_break("-")
    puts PASTEL.bright_green.bold "lifetime (alias life) - format: shifts lifetime NAME (returns cached lifetime report generated by glifetime command)"
    line_break("-")
    puts PASTEL.cyan.bold "rota (alias r) - format: shifts rota DATE"
  end

  private
  def self.get_date(input)
    date = define_period(input)
  rescue Date::Error
    abort "Invalid date input. Type 'shifts help' for help."
    date
  end

  def self.get_employees(date)
    client = Client.new
    employees = client.get_employees(date)
    employees
  end

  def self.line_break(char)
    puts "#{char}" * 50
  end
end
